
version: '3.9'

services:

  homeloniq-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homeloniq-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SPARK_MASTER_URL: "spark://spark-master:7077"       # optional, if used
      DELTA_STORAGE_PATH: "/mnt/gold/"
    volumes:
      - ./src/extraction/application_apis:/app
    depends_on:
      - spark-master
    restart: unless-stopped

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  # Optional: Azure CLI or Databricks CLI for integration
  databricks-cli:
    image: mcr.microsoft.com/azure-cli
    container_name: databricks-cli
    volumes:
      - ~/.azure:/root/.azure
    stdin_open: true
    tty: true

