endpoints:
  - path: /kpis/customer_summary
    source: gold_customer_kpi
    auth_required: true
    masking: true
    limit: 100

  - path: /influence/top_customers
    source: gold_customer_influence
    auth_required: true
    limit: 50

roles:
  analyst:
    access:
      - /kpis/customer_summary

  fraud_investigator:
    access:
      - /influence/top_customers
